name: zoomore
description: A new Flutter project.

version: 0.0.5+12
publish_to: none

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ^1.22.0

dependencies:
  flutter:
    sdk: flutter
  app_settings: 4.1.1
  infinite_scroll_pagination: 3.1.0
  cupertino_icons: ^0.1.3
  matrix_gesture_detector: 0.1.0
  image_picker: 0.6.7
  permission_handler: 5.1.0+2
  flutter_ffmpeg: 0.4.2
  path_provider:
  mutex: 3.0.0
  esys_flutter_share: 1.0.2
  image_gallery_saver: 1.6.9
  media_gallery:
    # Fixes issue: https://github.com/aloisdeniel/media_gallery/issues/28
    git:
      url: git://github.com/Geostry/media_gallery
      ref: f5b30c7298f01dcc1589b6ac450888010c0da9f3
  image: 2.1.14
  file: 5.2.1
  flutter_native_splash: ^0.1.9
  change_app_package_name: ^1.0.0
  get_it: ^7.2.0

dev_dependencies:
  flutter_launcher_icons: 0.8.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/large-image.jpg
    - assets/splash-200x200.png

flutter_native_splash:
  image: assets/splash-200x200.png
  color: "2196f3"
  android12: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/zoomore-icon-512x512.png"
  image_path_ios: "assets/zoomore-icon-opaque-512x512.png"
