name: zoomore
description: A new Flutter project.

version: 0.0.2+3

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ^1.22.0

dependencies:
  flutter:
    sdk: flutter
  # flutter_google_ad_manager: ^0.11.1
  cupertino_icons: ^0.1.3
  matrix_gesture_detector: 0.1.0
  provider: 4.3.2
  image_picker: 0.6.7
  permission_handler:
  # flutter_ffmpeg: ^0.3.0
  path_provider:
  esys_flutter_share: '1.0.2'
  image_gallery_saver: '^1.6.9'
  media_gallery:
    git:
      url: git://github.com/rignaneseleo/media_gallery
      ref: f277e8c5955bc824feb700600d641df75329124e
  image: 2.1.14
  file: 5.2.1
  flutter_native_splash: ^0.1.9
  change_app_package_name: ^1.0.0

dev_dependencies:
  flutter_launcher_icons: 0.8.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/large-image.jpg
    - assets/splash-200x200.png

flutter_native_splash:
  image: assets/splash-200x200.png
  color: "2196f3"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/zoomore-icon-512x512.png"
  