name: zoomore
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  matrix_gesture_detector: 0.1.0
  provider: 4.3.2
  image_picker: 0.6.7
  media_gallery:
    git:
      url: git://github.com/rignaneseleo/media_gallery
      ref: f277e8c5955bc824feb700600d641df75329124e
  screenshot: 0.2.0
  image: 2.1.14
  file: 5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/large-image.jpg
