import Head from "next/head";
import { FooterSection } from "../components/footer-section";
import { HeroSection } from "../components/hero-section";

export default function Page() {
  return (
    <>
      <HeroSection />

      <div className="max-w-7xl mx-auto py-12 px-4 sm:px-6 lg:px-8">
        <Head>
          <title>Zoomore - Privacy Policy</title>
        </Head>
        <h2 className="text-3xl">Privacy Policy</h2>
        <p>
          Ben Winding built the Zoomore app as a Free app. This SERVICE is
          provided by Ben Winding at no cost and is intended for use as is.
        </p>
        <p>
          This page is used to inform website visitors regarding my policies
          with the collection, use, and disclosure of Personal Information if
          anyone decided to use my Service.
        </p>
        <p>
          If you choose to use my Service, then you agree to the collection and
          use of information in relation to this policy. The Personal
          Information that I collect is used for providing and improving the
          Service. I will not use or share your information with anyone except
          as described in this Privacy Policy.
        </p>
        <p>
          The terms used in this Privacy Policy have the same meanings as in our
          Terms and Conditions, which is accessible at Zoomore unless otherwise
          defined in this Privacy Policy.
        </p>
        <p>
          <strong>Information Collection and Use</strong>
        </p>
        <p>
          This app does not collect user generated information in any way.
        </p>
        <p>
          The app does use third party services that may collect information
          used to identify you.
        </p>
        <p>
          <strong>Log Data</strong>
        </p>
        <p>
          I want to inform you that whenever you use my Service, in a case of an
          error in the app I collect data and information (through third party
          products) on your phone called Log Data. This Log Data may include
          information such as your device Internet Protocol (“IP”) address,
          device name, operating system version, the configuration of the app
          when utilizing my Service, the time and date of your use of the
          Service, and other statistics.
        </p>
        <p>
          <strong>Security</strong>
        </p>
        <p>
          I value your trust in providing us your Personal Information, thus we
          are striving to use commercially acceptable means of protecting it.
          But remember that no method of transmission over the internet, or
          method of electronic storage is 100% secure and reliable, and I cannot
          guarantee its absolute security.
        </p>
        <p>
          <strong>Changes to This Privacy Policy</strong>
        </p>
        <p>
          I may update our Privacy Policy from time to time. Thus, you are
          advised to review this page periodically for any changes. I will
          notify you of any changes by posting the new Privacy Policy on this
          page. These changes are effective immediately after they are posted on
          this page.
        </p>
        <p>
          <strong>Contact Us</strong>
        </p>
        <p>
          If you have any questions or suggestions about my Privacy Policy, do
          not hesitate to contact me.
        </p>
        <p>
          This privacy policy page was created at
          <a href="https://privacypolicytemplate.net/" target="_blank">
            privacypolicytemplate.net
          </a>
          and modified/generated by
          <a
            href="https://app-privacy-policy-generator.firebaseapp.com/"
            target="_blank"
          >
            App Privacy Policy Generator
          </a>
        </p>
      </div>
      <FooterSection />
    </>
  );
}
